# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e401ca22b6695828c90eb076fe5420b4bc34b7a7d4429308cd7d908a136e796c91ea01eeb7422eb3cb7678b2121024a78376a20c115a4f5ae1ed7f3ce14d7e67

test:
  secret_key_base: 277ec2bb264aacaf082007cc9c79cd80a46e5b03735b9a15a75c591141dcbfb8744ee0ff74fd62f6356c043467a453dfee9f875b2bca3692ea22892f2b2787c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
